language: node_js
node_js:
  - "12"
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=diegopovalz-github -Dsonar.projectKey=lab22022 -Dsonar.sources='./app' -X
