language: node_js
node_js:
  - "12"
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - npm run cover
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=poveda-github-arqui -Dsonar.projectKey=lab22022-v2 -Dsonar.sources='./app' -X
after_success:
  - npm run coveralls
